### 创建角色
POST {{host}}/role/createRole
Content-Type: application/json

{
  "name": "新建角色带权限123456",
  "description": "测试聚合描述",
  "permissionCodes": [
    "permission:create",
    "permission:update",
    "permission:delete"
  ]
}

### 获取所有角色
POST {{host}}/role/getAllRoles

### 根据条件获取角色
POST {{host}}/role/getRolesByCondition
Content-Type: application/json

{
  "description": "cd"
}

### 获取角色详情
POST {{host}}/role/getRoleById
Content-Type: application/json

205809655577587712

### 获取角色权限
POST {{host}}/role/getRolePermissionsById
Content-Type: application/json

205809655577587712

### 更新角色信息
POST {{host}}/role/updateRoleInfo
Content-Type: application/json

{
  "roleId": 205809655577587712,
  "description": "没有你也更新？"
}

### 更新角色权限
POST {{host}}/role/updateRolePermissions
Content-Type: application/json

{
  "roleId": 205809655577587712,
  "permissionCodes": [
    "permission:create",
    "permission:update"
  ]
}

### 删除角色
POST {{host}}/role/deleteRole
Content-Type: application/json

[
  205809655577587712
]
