### 架构信息
POST {{host}}/cap4k/archinfo

### 事件查询
POST {{host}}/cap4j/console/event/search?
    uuid=
    #    &type=
    #    &state=
    #    &scheduleAt=
    #    &scheduleAt=
    #    &pageSize=
    #    &pageNum=



### 事件重试
POST {{host}}/cap4j/console/event/retry?
    uuid=



### 请求查询
POST {{host}}/cap4j/console/request/search?
    uuid=
    &type=
&state=
&scheduleAt=
&scheduleAt=
&pageSize=
&pageNum=



### 请求重试
POST {{host}}/cap4j/console/request/retry?
    uuid=
